---
title: "Analysis"
output:  
  html_document:
    number_sections: true
    toc: true  
    collapsed: false
    toc_float: true
    smooth_scroll: false
    toc_depth: 3
---

```{r, message = FALSE, echo = FALSE, warning=FALSE}
# packages
library(reshape2)
library(ggplot2)
library(plyr)
library(ez)
library(psych)
```


```{r}
# function 
rFromWilcox<-function(p,N){
  z<-qnorm(p/2)
  r<-z/sqrt(N)
  return(r)
}
```

# Data preparation

```{r}
# read data 
tdata <- read.delim("02_tdata.txt",header=FALSE)
sdata <- read.delim("02_sdata.txt",header=FALSE)
```


```{r}
# reshape data -----------------------------------------------------------

names(tdata)<-c("sID","cond","variable","value")
names(sdata)<-c("sID","sex","age","duration","cond","dispcode")
tdata <- tdata[with(tdata, order(sID)),]
sdata <- sdata[with(sdata, order(sID)),]
tdata$sID <- as.factor(tdata$sID)
tdata$cond <- as.factor(tdata$cond)
tdata$variable <- as.factor(tdata$variable)
tdata$value <- tdata$value-1

tdata.wide <- dcast(tdata,sID+cond~variable)

# has the small object elicited the left or the right balloon?

for (i in 1:dim(tdata.wide)[1]){
  if(tdata.wide$cond[i]=="contr_smL"|tdata.wide$cond[i]=="size") tdata.wide$obs[i]<-"smL"
  else tdata.wide$obs[i]<-"smR"
}

# test whether causal questions were answered correctly

for (i in 1:dim(tdata.wide)[1]){
  if((tdata.wide$obs[i]=="smL"&tdata.wide$cause_largeHeavy[i]==1&tdata.wide$cause_smallLight[i]==0)|(tdata.wide$obs[i]=="smR"&tdata.wide$cause_largeHeavy[i]==0&tdata.wide$cause_smallLight[i]==1)) tdata.wide$causeCorr[i]<-1
  else tdata.wide$causeCorr[i]<-0
}

# test whether prediction was made according to size or weight (0 = size, 1 = weight)

for (i in 1:dim(tdata.wide)[1]){
    if ((tdata.wide$obs[i]=="smL"&tdata.wide$pred_smallHeavy[i]==0)|(tdata.wide$obs[i]=="smR"&tdata.wide$pred_smallHeavy[i]==1)) tdata.wide$predDisp_smallHeavy[i]<-0
    else tdata.wide$predDisp_smallHeavy[i]<-1
}

for (i in 1:dim(tdata.wide)[1]){
  if ((tdata.wide$obs[i]=="smL"&tdata.wide$pred_largeLight[i]==1)|(tdata.wide$obs[i]=="smR"&tdata.wide$pred_largeLight[i]==0)) tdata.wide$predDisp_largeLight[i]<-0
  else tdata.wide$predDisp_largeLight[i]<-1
}

# test whether both predictions are consistent

for (i in 1:dim(tdata.wide)[1]){
  if (tdata.wide$predDisp_smallHeavy[i]==tdata.wide$predDisp_largeLight[i]) tdata.wide$predCons[i]<-1
  else tdata.wide$predCons[i]<-0
}

tdata.wide$predDisp<-rowMeans(tdata.wide[,11:12])
tdata.wide$obs<-as.factor(tdata.wide$obs)
levels(tdata.wide$cond)<-c(rep("Control",2),"Size","Weight")
tdata.wide$conf_mean<-rowMeans(tdata.wide[,5:6])
```



# Graphs 

## predictions

```{r}
# plot of predictions ------------------------------------------------------

# data <- subset(tdata.wide,select=c("sID","cond","predDisp"))
data <- subset(tdata.wide,subset=causeCorr==1,select=c("sID","cond","predDisp"))
# data <- subset(tdata.wide,subset=(causeCorr==1&predCons==1),select=c("sID","cond","predDisp"))

names(data)[3]<-"value"

df.summary <- ddply(data,.(cond),function(df)c(mean(df$value),sd(df$value),length(df$value))) # ddply is from plyr
names(df.summary) <- c("condition","mean","sd","n")
df.summary$MOE.95 <- (df.summary$sd/sqrt(df.summary$n))*qnorm(.975,0,1)
df.summary$UB.95 <- df.summary$mean+df.summary$MOE.95
df.summary$LB.95 <- df.summary$mean-df.summary$MOE.95

bar.summary <- ggplot(df.summary,aes(condition,mean))
bar.summary+ 
  coord_cartesian(ylim=c(0,1))+ 
  scale_y_continuous(limits=c(-.2,1.2),breaks=seq(0,1,.1))+
  scale_x_discrete(labels=levels(df.summary$condition))+
  geom_bar(stat="identity",position="dodge",colour="black",fill="light grey")+
  geom_errorbar(mapping=aes(ymin=LB.95,ymax=UB.95),stat="identity",position=position_dodge(width=.9),width=.2)+
  geom_hline(data=NULL, aes(yintercept=.5), linetype = "dashed", size=.5)+
  geom_text(aes(y=.04,label=n),colour="black",size=4)+
  # ggtitle("Results")+
  theme(plot.title=element_text(face="bold",size=12),
        axis.title.x=element_text(face="bold",size=12),
        axis.title.y=element_text(face="bold",size=12),
        axis.text.x=element_text(size=12), 
        axis.text.y=element_text(size=12),
        legend.text=element_text(size=12),
        legend.title=element_text(face="bold",size=12),
        strip.text.x=element_text(size=12),
        strip.text.y=element_text(size=12),
        strip.background=element_rect(colour="black",fill="light grey"),
        legend.position=c(0.75,0.85),
        panel.grid.major=element_blank(), 
        panel.grid.minor=element_blank(), 
        panel.background=element_blank(), 
        axis.line=element_line(colour="black"), 
        axis.text=element_text(colour="black"), 
        axis.ticks=element_line(colour="black"))+ 
  labs(x="Condition",y="Size <--> Weight")

#ggsave("01_results.tiff",height=10,width=10,units="cm",dpi=1200)
```


## confidence ratings

```{r}
# plot of confidence ratings ----------------------------------------------

# data.conf <- subset(tdata.wide,select=c(sID,cond,conf_largeLight,conf_smallHeavy))
data.conf <- subset(tdata.wide,subset=causeCorr==1,select=c(sID,cond,conf_largeLight,conf_smallHeavy))
data.conf <- melt(data.conf,id=c("sID","cond"),measured=c("conf_largeLight","conf_smallHeavy"))

df.conf <- ddply(data.conf,.(cond,variable),function(df)c(mean(df$value),sd(df$value),length(df$value)))
names(df.conf) <- c("condition","variable","mean","sd","n")
df.conf$MOE.95 <- (df.conf$sd/sqrt(df.conf$n))*qnorm(.975,0,1)
df.conf$UB.95 <- df.conf$mean+df.conf$MOE.95
df.conf$LB.95 <- df.conf$mean-df.conf$MOE.95

bar.conf <- ggplot(df.conf,aes(condition,mean,fill=variable))
bar.conf+ 
  coord_cartesian(ylim=c(1,10))+ 
  scale_y_continuous(limits=c(0,10),breaks=seq(0,10,1))+
  scale_x_discrete(labels=levels(df.conf$condition))+
  geom_bar(stat="identity",position="dodge",colour="black")+
  geom_errorbar(mapping=aes(ymin=LB.95,ymax=UB.95),stat="identity",position=position_dodge(width=.9),width=.2)+
  geom_text(aes(y=1.5,label=n),colour="black",position=position_dodge(width=.9),size=4)+
  # ggtitle("Results")+
  theme(plot.title=element_text(face="bold",size=12),
        axis.title.x=element_text(face="bold",size=12),
        axis.title.y=element_text(face="bold",size=12),
        axis.text.x=element_text(size=12), 
        axis.text.y=element_text(size=12),
        legend.text=element_text(size=12),
        legend.title=element_text(face="bold",size=12),
        strip.text.x=element_text(size=12),
        strip.text.y=element_text(size=12),
        strip.background=element_rect(colour="black",fill="light grey"),
        legend.position=c(0.25,0.85),
        panel.grid.major=element_blank(), 
        panel.grid.minor=element_blank(), 
        panel.background=element_blank(), 
        axis.line=element_line(colour="black"), 
        axis.text=element_text(colour="black"), 
        axis.ticks=element_line(colour="black"))+ 
  labs(x="Condition",y="Confidence")+
  scale_fill_manual(values=c("#696969","#999999"),name="Test Object",labels=c("large & light","small & heavy"))

#ggsave("01_confidence.tiff",height=10,width=10,units="cm",dpi=1200)
```

# Statistical analysis 

## Descriptive stats

```{r}
# statistics --------------------------------------------------------------

# data <- subset(tdata.wide,select=c("sID","cond","obs","predDisp"))
data <- subset(tdata.wide,subset=causeCorr==1,select=c("sID","cond","obs","predDisp"))
# data <- subset(tdata.wide,subset=(causeCorr==1&predCons==1),select=c("sID","cond","obs","predDisp"))

names(data)[4]<-"value"

# descriptive statistics of predicitons by conditon

by(data$value,data$cond,describe)
```

## Wilcoxon signed rank tests against .5 by condition
```{r}
# Wilcoxon signed rank tests against .5 by condition

wilc.vs0.5<-by(data$value,data[,2],wilcox.test,mu=0.5)
wilc.vs0.5<-data.frame(do.call(rbind,wilc.vs0.5))[,c(1,3)]
wilc.vs0.5$statistic<-as.numeric(wilc.vs0.5$statistic)
wilc.vs0.5$p.value<-as.numeric(wilc.vs0.5$p.value)
wilc.vs0.5$n<-by(data$value,data[,2],length)
wilc.vs0.5$n<-as.numeric(wilc.vs0.5$n)
wilc.vs0.5$r<-rFromWilcox(wilc.vs0.5$p.value,wilc.vs0.5$n)
wilc.vs0.5$condition<-c("Control","Size","Weight")
(wilc.vs0.5<-wilc.vs0.5[,c(5,3,1,2,4)])
```

Get the CIs for the r values:

- Condition: Size

```{r}
#devtools::install_github("TiagoOlivoto/metan")
library(metan) 
corr_ci(   
  r = 0.7097688,
  n = 36,
  verbose = TRUE
)

#Computes the half-width confidence interval for correlation coefficient using the nonparametric method proposed by Olivoto et al. (2018). see: https://rdrr.io/cran/metan/man/corr_ci.html


0.7097688 - 0.2132 # lower boundary 
0.7097688 + 0.2132 # upper boundary 

```
- Condition: Weight

```{r}
corr_ci(   
  r = 0.6701814,
  n = 34,
  verbose = TRUE
)

0.6701814 - 0.2264
0.6701814 + 0.2264
```




## test of effect of counterbalancing cause-effect associations within control condition
```{r}
# test of effect of counterbalancing cause-effect associations within control condition

wilc.contr<-wilcox.test(data$value[data$cond=="Control"]~data$obs[data$cond=="Control"])
wilc.contr
rFromWilcox(wilc.contr$p.value,dim(data)[1])
```

## One-way ANOVA on confidence ratings
```{r}
# One-way ANOVA on confidence ratings

anova.conf <- ezANOVA(data.conf, dv = .(value), wid = .(sID), between = .(cond), within = .(variable), type = 3, detailed = TRUE)
anova.conf
```






